name: CI-CD

on:
  create:
    branches: [hotfix/*, release/*]
  pull_request:
    branches: [develop, hotfix/*, release/*]
    types: [opened, reopened, edited, synchronize]
env:
  SOLUTION_NAME: TestGithubActionOnXamarin
  ANDROID_PROJECT_NAME: TestGithubActionOnXamarin.Android

jobs:
  test:
    name: Setup Xamarin and Mono versions
    runs-on: macos-latest
    steps:
      - name: setup-xamarin
        uses: maxim-lobanov/setup-xamarin@v1
        with:
          mono-version: "latest" # specify version in '<major>.<minor>' format
          xamarin-ios-version: "latest" # specify version in '<major>' format
          xamarin-mac-version: latest # specify 'latest' keyword to pick up the latest available version
          xamarin-android-version: "latest" # specify full version; it is not recomended option because your pipeline can be broken suddenly in future
          xcode-version: "latest" # set the latest available Xcode 11
      - uses: actions/checkout@v2
      - name: Test
        run: dotnet test TestGithubActionOnXamarin.UnitTest
  Android:
    runs-on: macos-latest    
    steps:
    - uses: actions/checkout@v1      
    - name: Android
      run: |
        nuget restore
        msbuild TestGithubActionOnXamarin.Android/TestGithubActionOnXamarin.Android.csproj /verbosity:normal /t:Rebuild /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Debug 
    - name: Get branch name (pull request)
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v2
      with:
        name: Android Apk ${{ env.BRANCH_NAME }}
        path: TestGithubActionOnXamarin.Android/bin/Debug/br.com.aismaniotto.testgithubactiononxamarin-Signed.apk

