name: CI-CD

on:
  pull_request:
    branches: [develop, hotfix/*, release/*]
    types: [opened, reopened, edited, synchronize]
env:
  SOLUTION_NAME: TestGithubActionOnXamarin
  ANDROID_PROJECT_NAME: TestGithubActionOnXamarin.Android

jobs:
  test:
    name: Setup Xamarin and Mono versions
    runs-on: macos-latest
    steps:
      - name: setup-xamarin
        uses: maxim-lobanov/setup-xamarin@v1
        with:
          mono-version: "latest" # specify version in '<major>.<minor>' format
          xamarin-ios-version: "latest" # specify version in '<major>' format
          xamarin-mac-version: latest # specify 'latest' keyword to pick up the latest available version
          xamarin-android-version: "latest" # specify full version; it is not recomended option because your pipeline can be broken suddenly in future
          xcode-version: "latest" # set the latest available Xcode 11
      - uses: actions/checkout@v2
      - name: Test
        run: dotnet test TestGithubActionOnXamarin.UnitTest
  Android:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Building APK
        uses: ./action
        with:
          args: /r:True /t:SignAndroidPackage /p:AndroidSdkDirectory=/android/sdk ${{env.SOLUTION_NAME}}/${{env.ANDROID_PROJECT_NAME}}/${{env.ANDROID_PROJECT_NAME}}.csproj
      - name: Artifacts
        run: |
          mkdir -p apks
          cp ${{env.SOLUTION_NAME}}/${{env.ANDROID_PROJECT_NAME}}/bin/Debug/*.apk apks
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: apks
          path: apks
